---
- name: Show kernel version (pre-update)
  ansible.builtin.command: uname -a
  register: kernelpre
  changed_when: false

- name: Print kernel version
  ansible.builtin.debug:
    msg: "{{ kernelpre.stdout }}"

- name: Check time
  ansible.builtin.command: date
  register: datepre
  changed_when: false

- name: Display time before sync
  ansible.builtin.debug:
    msg: "{{ datepre.stdout }}"
